### PR TITLE
Add options to model creation

### PR DESCRIPTION
**Pull request by ghost**
Project needs a new compilation - tried it in various ways on windows but nothing worked, thanks :)

### CODE REVIEW

**Comment by nilbus** [comment]
Nice. Have you tested and found this to resolve your problem?

**Comment by nilbus** [comment]
Seems to me like it should. Thanks! :-)

**Comment by paaddyy** [comment]
thanks for merging and compiling :) 
like you're repo, does a great job in my project :)

**Comment by nilbus** [comment]
@paaddyy Glad to hear! You certainly made it easy with your PR. How long have you been using it? I have been wondering if there are any new users, with React taking over the world these days.

**Comment by paaddyy** [comment]
Haha, I never tried React :D I think I'll give Vue a chance within the next days, seems it has the potential to combine all the best features from Angular and React. Do you still use Backbone or have you changed your "stack" too? :)

I'm using it at work for three weeks now. At the moment only for Localstorage but within the next few weeks also for server sync. I'm excited if everthing works directly :P

**Comment by nilbus** [comment]
Despite the maintenance I've put in for this project, I haven't used
Backbone for 4 years.

Good luck with your project!

**Pull request merged**
